# -*- coding: utf-8 -*-
"""AI2_Multi Neuron Batch Input.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dn8Ier6PzGi9z8vGAAzHfX6HAPVD7ktm
"""

#Sayyidina Auliya
#21091397034

#inisialisasi numpy sebagai library
import numpy as np

#input layer feature 10
#per-batchnya ada 6 input
inputs = [
    [0.2,-0.6,0.9,-0.19,0.99,0.06,0.98,-0.29,0.3,0.68],
    [0.35,0.63,-0.28,0.47,-0.98,0.57,0.23,0.36,-0.69,0.85],
    [0.1,0.7,0.25,-0.8,0.61,-0.11,0.32,0.21,0.5,-0.9],
    [-0.94,0.52,0.50,0.95,-0.77,0.04,-0.93,0.56,0.27,0.97],
    [0.05,-0.06,0.11,0.84,0.96,-0.084,0.30,-0.19,0.290,0.69],
    [0.33,0.74,-0.75,0.32,0.85,0.12,-0.80,0.002,-0.460,0.4]
]

#hidden layer 1, 5 neuron
weights = [
    [0.51,0.07,0.99,0.28,0.91,0.34,0.01,0.46,0.88,0.02],
    [0.79,0.73,0.67,0.61,0.54,0.48,0.42,0.36,0.17,0.41],
    [0.14,0.77,0.08,0.71,0.38,0.78,0.37,0.75,0.33,0.93],
    [0.69,0.19,0.90,0.24,0.78,0.73,0.67,0.49,0.97,0.45],
    [0.86,0.15,0.80,0.32,0.55,0.35,0.83,0.42,0.88,0.29]
]

biases = [5.0,7.4,0.9,1.7,1.4]

#hidden layer 2, 3 neuron
weights2 = [
    [0.10,0.42,0.02,0.7,0.33],
    [0.50,0.55,0.15,0.37,0.99],
    [0.31,0.82,0.59,0.44,0.13]
]

biases2 = [2.4,0.7,5.3]

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases
layer2_outputs = np.dot(layer1_outputs, np.array (weights2).T) + biases2

print(layer2_outputs)